"""fix

Revision ID: 25ebc61cf88b
Revises: 205b9e556e16
Create Date: 2025-08-01 17:30:15.345703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ebc61cf88b'
down_revision = '205b9e556e16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
